version: '3.1'
services:
    mysql:
        image: 'mysql'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=root_pass
            - MYSQL_DATABASE=app_db
            - MYSQL_USER=app_db_user
            - MYSQL_PASSWORD=app_db_pass
        ports:
            - '29002:3306'

    rabbitmq:
        image: 'rabbitmq'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=root_pass
            - MYSQL_DATABASE=app_db
            - MYSQL_USER=app_db_user
            - MYSQL_PASSWORD=app_db_pass
        ports:
            - '29002:3306'

    # TODO: volume
    sender:
        container_name: sender
        entrypoint:
            - /app/sender.py
        image: 'python'
        working_dir: /app

    parser:
        container_name: parser
        entrypoint:
            - /app/parser.py
        image: 'python'
        working_dir: /app

    reader:
        container_name: reader
        entrypoint:
            - /app/reader.py
        image: 'python'
        working_dir: /app
    
    error_handler:
        container_name: error_handler
        entrypoint:
            - /app/error_handler.py
        image: 'python'
        working_dir: /app
    
    generator:
        container_name: generator
        entrypoint:
            - /app/generator.py
        image: 'python'
        working_dir: /app