version: '3.1'
services:
    mysql:
        image: 'mysql'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=root_pass
            - MYSQL_DATABASE=wordsbase
            - MYSQL_USER=av_user
            - MYSQL_PASSWORD=password
        ports:
            - '29002:3306'

    rabbitmq:
        image: 'rabbitmq'
        working_dir: /app
        volumes:
            - '.:/app'
        ports:
            - "15672:15672"
            - "5672:5672"

    # TODO: volume
    sender:
        container_name: sender
        entrypoint:
            - /app/sender.py
        environment:
            - RABBITMQ_HOST=localhost
            - RABBITMQ_PORT=5672
            - RABBITMQ_EXCHANGE=avsoft
            - MYSQL_USER=av_user
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=wordsbase
        image: 'python3'
        working_dir: /app

    parser:
        container_name: parser
        entrypoint:
            - /app/parser.py
        environment:
            - RABBITMQ_HOST=localhost
            - RABBITMQ_PORT=5672
            - RABBITMQ_EXCHANGE=avsoft
            - MYSQL_USER=av_user
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=wordsbase
        image: 'python3'
        working_dir: /app

    reader:
        container_name: reader
        entrypoint:
            - /app/reader.py
        environment:
            - MYSQL_USER=av_user
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=wordsbase
        image: 'python3'
        working_dir: /app
    
    error_handler:
        container_name: error_handler
        entrypoint:
            - /app/error_handler.py
        environment:
            - RABBITMQ_HOST=localhost
            - RABBITMQ_PORT=5672
            - RABBITMQ_EXCHANGE=avsoft
            - TELEGRAM_TOKEN=token
            - TELEGRAM_CHAT_IDS=1,2,3
        image: 'python3'
        working_dir: /app
    
    generator:
        container_name: generator
        entrypoint:
            - /app/generator.py
        image: 'python3'
        working_dir: /app