version: '3'
services:
    mysql:
        image: 'mysql'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=root_pass
            - MYSQL_DATABASE=wordsbase
            - MYSQL_USER=av_user
            - MYSQL_PASSWORD=password
        ports:
            - '3306:3306'

    rabbitmq:
        image: 'rabbitmq'
        working_dir: /app
        volumes:
            - '.:/app'
        ports:
            - "15672:15672"
            - "5672:5672"

    # TODO: volume
    sender:
        container_name: sender
        command: python3 /app/sender.py
        environment:
            - RABBITMQ_HOST=localhost
            - RABBITMQ_PORT=5672
            - RABBITMQ_EXCHANGE=avsoft
            - MYSQL_USER=av_user
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=wordsbase
        image: 'python3'
        working_dir: /app
        volumes:
            - '/app/watching:/watching'
        depends_on:
            - mysql
            - rabbitmq
            - error_handler
            - parser

    parser:
        container_name: parser
        command: python3 /app/parser.py
        environment:
            - RABBITMQ_HOST=localhost
            - RABBITMQ_PORT=5672
            - RABBITMQ_EXCHANGE=avsoft
            - MYSQL_USER=av_user
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=wordsbase
        image: 'python3'
        working_dir: /app
        volumes:
            - '/app/watching:/watching'
        depends_on:
            - mysql
            - rabbitmq

    reader:
        container_name: reader
        command: python3 /app/reader.py
        environment:
            - MYSQL_USER=av_user
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=wordsbase
        image: 'python3'
        working_dir: /app
        depends_on:
            - mysql
            - parser
    
    # TODO: volume for output
    error_handler:
        container_name: error_handler
        command: python3 /app/error_handler.py
        environment:
            - RABBITMQ_HOST=localhost
            - RABBITMQ_PORT=5672
            - RABBITMQ_EXCHANGE=avsoft
            - TELEGRAM_TOKEN=token
            - TELEGRAM_CHAT_IDS=1,2,3
        image: 'python3'
        working_dir: /app
        depends_on:
            - rabbitmq
    
    generator:
        container_name: generator
        command: python3 /app/generator.py
        image: 'python3'
        working_dir: /app
        volumes:
            - '/app/watching:/watching'
        depends_on:
            - parser